### ISSUE TITLE
タイマーが止まっているかではなく、時間を更新するかで場合分けする。

### ISSUE THREAD

**Issue by Saku35** [Saku35/Timer#12]
is_stopで時間の更新を制御するのではなく、更新するかどうかで時間を更新しよう。
確かに、「時間を更新するかどうか」でしか時間は更新できない気がする。
そもそもis_stopが時間の更新を制御していることに気づいてなかった。

**Comment by vestige** [comment]
まずは、いまある変数の定義を整理する

**Comment by vestige** [comment]
一応、動くところまで書いてみたが、変数が多い・・・

https://gist.github.com/vestige/6ea9de3faaa6cbc7d0676e231c68e2e3

**Comment by vestige** [comment]
なんかこれはこれで微妙なので気にせずに。
とりあえず、少し直したものをプルリクしたー

**Comment by Saku35** [comment]
プルリクありがとうございました！

時間の更新について考えてみましたので、暇な時リンクみてみてくださいー。
https://user-images.githubusercontent.com/47977293/58384156-8f67e800-8019-11e9-8e3b-4096063571db.jpg

**Comment by vestige** [comment]
みた！
すごい綺麗なメモでびっくりした :)
たしかに前回の時間が必要そうな感じするね。
gistのコードみた？
このやり方はどう思う？

**Comment by vestige** [comment]
とりあえずはいまのままで進んでみることにいったんクローズして < @Saku35

**Comment by Saku35** [comment]
ありがとうございます。
クローズします。
