### ISSUE TITLE
タイマースタート・ストップ

### ISSUE THREAD

**Issue by Saku35** [Saku35/Timer#5]
キーが押されたらスタート、ストップするようにする。
トグル的な動作にしたいから、スペースキーでどちらもできるように。

**Comment by vestige** [comment]
いまのバージョンはそれでいいかもだけど、間違えて連続でおしちゃったり、動いているかどうかがわからなくなるような気がして、押し間違えることも考えると同じキーでスタートストップはちょっと考えものかもしれない。

**Comment by Saku35** [comment]
スタート・ストップのボタンを分ける。
スタート：aキー
ストップ：zキー
