### ISSUE TITLE
計測する時刻を設定できるようにする。

### ISSUE THREAD

**Issue by Saku35** [Saku35/Timer#7]
「タイマースタート待ち」状態と、「一時停止」状態、「カウント終了」状態を区別して、タイマースタート待ち状態でのみ時刻設定をできるようにします。

**Comment by Saku35** [comment]
分単位で増減するminuteAdd()関数も作った。

**Comment by vestige** [comment]
#16 でまずはプリセットにするようにしたい。

**Comment by Saku35** [comment]
#16でプリセットを作ったので、クローズ
